# Generated by Django 4.2.5 on 2023-09-25 03:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('tripID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('volumeToBeUsed', models.DecimalField(decimal_places=4, default=0.0, max_digits=4)),
                ('date', models.DateField(auto_now_add=True)),
                ('VIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.vehicle')),
            ],
        ),
    ]
