# Generated by Django 4.2.5 on 2023-09-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_user_email_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='volumeToBeUsed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
