# Generated by Django 4.2.5 on 2023-09-25 11:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_trip_volumetobeused'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('driverID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('licence_no', models.PositiveIntegerField()),
                ('VIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.vehicle')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('monitor.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
