# Generated by Django 4.2.5 on 2023-09-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('DRIVER', 'DRIVER')], max_length=10),
        ),
    ]
