# Generated by Django 4.2.5 on 2023-09-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='roles',
            field=models.CharField(default='DRIVER', max_length=20),
        ),
    ]
