# Generated by Django 4.2.5 on 2023-09-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_driver_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='roles',
        ),
    ]
