# Generated by Django 4.2.5 on 2024-06-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_receiveddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiveddata',
            name='data',
        ),
        migrations.RemoveField(
            model_name='receiveddata',
            name='received_at',
        ),
        migrations.AddField(
            model_name='receiveddata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receiveddata',
            name='device_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='receiveddata',
            name='raw_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='receiveddata',
            name='sensor_value',
            field=models.IntegerField(null=True),
        ),
    ]
