# Generated by Django 4.2.5 on 2024-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_remove_receiveddata_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('device_id', models.CharField(max_length=100)),
                ('IMEI', models.CharField(max_length=15)),
                ('time', models.DateTimeField()),
                ('latitude_degrees', models.FloatField()),
                ('longitude_degrees', models.FloatField()),
                ('altitude', models.FloatField()),
                ('course', models.FloatField()),
                ('speed_km_per_hour', models.FloatField()),
                ('alarm_status', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('mileage', models.FloatField()),
                ('gsm_signal', models.IntegerField()),
                ('fuel_levels_percentage', models.FloatField()),
                ('engine_hours', models.FloatField()),
                ('power_level_volts', models.FloatField()),
            ],
        ),
    ]
